### ISSUE TITLE
菜鸟提问，编译时问题

### ISSUE THREAD

**Issue by 848571678** [iSpring/WebGlobe#39]
error TS18003: No inputs were found in config file '*****/tsconfig.json'. Specified 'include' paths were '["ts/**/*.ts"]' and 'exclude' paths were '["node_modules"]'.

**Comment by iSpring** [comment]
请确保是develop分支上最新的代码，确保通过npm install安装了所需要的npm包，然后WebGlobe项目的根目录执行npm start就行了，我没有遇到你的编译问题，Windows7和Ubuntu14.04上面我都能编译通过，编译不需要安装VisualStudioCode，VisualStudioCode只是用来写代码的文本编辑器。
 具体问题可以到 https://gitter.im/iSpring/WebGlobe 里面讨论，这样方便些。
