### ISSUE TITLE
【讨论请教】请教一个算法问题，计算tile块在不同高度占据的屏幕投影面积

### ISSUE THREAD

**Issue by QingMings** [iSpring/WebGlobe#54]
主要是想用来实现 
LOD，目前在做一些[webWorldWind](https://github.com/NASAWorldWind/WebWorldWind)的一些工作，这个对`KML`的支持不太全，加载`Region`时候一次性加载了所有的图片，不符合性能要求，想改成支持`LOD`的，不太会计算`tile`块在不同高度下的`屏幕投影面积`。请教一下，希望能指点一二。

**Comment by iSpring** [comment]
@QingMings 这是一个好问题，也是三维地球实现的一个难点。

我是这么计算切片的投影面积的：
1.  一个切片有四个角点，分别是ABCD，我们需要分别计算着四个点最终在屏幕上的屏幕坐标。

2.  问题的难点就在于怎么把一个三维直角坐标系中的点转换成屏幕坐标。我之前在CSDN上写过[《OpenGL中的坐标变换、矩阵变换》](http://blog.csdn.net/iispring/article/details/27970937)的文章，里面写的比较清楚。这里简单说一下：

    -  模型坐标系中的三维坐标乘以模型矩阵转换为世界坐标系中的坐标，WebGlobe中的模型矩阵都是单位矩阵，所以这一步在WebGlobe中可以忽略。

    -  世界坐标系中的坐标通过Camera的模型矩阵转换为Camera坐标系中的坐标。

    -  Camera坐标系中的坐标根据投影坐标系进行转换，将转换后的坐标进行归一化处理，得到归一化坐标，归一化坐标的范围是[-1, 1]。

    -  得到归一化坐标后，将其根据Canvas的width和height映射成Canvas坐标。

3. 这样我们就得到了ABCD四个点的Canvas坐标，这样就可以计算这四个点在Canvas屏幕上的面积，如果这个面积小于一定的阈值，那么我们就可以假设这个切片不可见。

除了计算面积之外，我还额外加了两个限定条件：1. 切片至少要有一个点在屏幕中可见；2. 切片的四个顶点是顺时针方向。

具体代码你可以考Camera中的[getVisibleTilesByLevel()](https://github.com/iSpring/WebGlobe/blob/develop/src/world/Camera.ts#L958)和[_getTileVisibleInfo()](https://github.com/iSpring/WebGlobe/blob/develop/src/world/Camera.ts#L1079)这两个方法，后面这个方法会判断一个切片在当前状态下是否应该可见，前者会调用后者，计算出某一级别下所有可见的切片。

我计算的出的切片在垂直视角下，最大level的切片里面一般都是16-20个切片左右。

**Comment by iSpring** [comment]
@QingMings 兄弟，帮忙给推广一下我这个小项目啊

**Comment by QingMings** [comment]
好的，讲的很清楚，很容易理解，求推荐相关书籍入门。😀

**Comment by iSpring** [comment]
@QingMings 你可以看看知乎上有人的回答，感觉不错https://www.zhihu.com/question/26521256/answer/63869753

  ● WebGL Beginner's Guide 入门书籍，这本书写的挺不错，网上应该有电子版
  ● WebGL高级编程，这本书也不错

**Comment by QingMings** [comment]
好的
