### ISSUE TITLE
你好，请教一下，TileGrid.getTileGridByGeo()的原理是什么，里面有什么公式吗

### ISSUE THREAD

**Issue by pp123pp** [iSpring/WebGlobe#55]

**Comment by iSpring** [comment]
@pp123pp TileGrid.getTileGridByGeo()这个方法就是判断一个经纬度在level层级下的切片索引号，即输入是(lon, lat, level)，输出是(level, row, column)，之前在我在博客中提到过一些推导过程，你可以看看
http://blog.csdn.net/iispring/article/details/9155267

**Comment by hizoubin** [comment]
@iSpring  请问为什么要用tileGrid这个类呢？它是代表每次9张切片数据吗
