### ISSUE TITLE
问一个问题, 百度卫星地图有吗？

### ISSUE THREAD

**Issue by fb783303646** [iSpring/WebGlobe#91]
问一个问题, 百度卫星地图有吗？就是说百度卫星地图能用做为openlayer3底图吗？能的话怎么用？跪求!

**Comment by iSpring** [comment]
@fb783303646 现在不支持百度的卫星地图，百度坐标系跟正常的不太一样，做了额外的偏移，我也没有深入研究百度卫星影像的切片规则

**Comment by bingo456** [comment]
问一下，请问影像地图能不能做到像Google地球那样的三维显示，谢谢~

**Comment by iSpring** [comment]
@bingo456 以前做过这样的效果，但是获取三维高程的服务太慢了，我就把它移除掉了，现在不支持了

**Comment by hizoubin** [comment]
@iSpring  有地形的这个版本是哪个版本呢？可否放出代码让我膜拜学习一下。谢谢
