### ISSUE TITLE
在buildOutput文件夹下构建的index.2459e6837d865f2e46c1.js之前的源文件是哪一个？

### ISSUE THREAD

**Issue by yanhuiDevelopers** [iSpring/WebGlobe#93]

**Comment by iSpring** [comment]
对应的入口文件是src/core/index.ts，可以参见webpack.config.js中的配置代码
https://github.com/iSpring/WebGlobe/blob/develop/webpack.config.js#L49

![image](https://user-images.githubusercontent.com/1745265/34157951-929d2a42-e4fe-11e7-8df9-1e70a89e5734.png)
